package com.example.nebeng.feature_a_homepage.domain.session.customer.nebeng_motor

import com.example.nebeng.core.utils.VehicleType
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.CustomerCurrentCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.DriverCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerPricingCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerRideBookingCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerRideCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PassengerTransactionCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.PaymentMethodCustomer
import com.example.nebeng.feature_a_homepage.domain.model.nebeng_motor.customer.TerminalCustomer
import java.time.LocalDate

data class BookingSession(
    // =========================
    // CUSTOMER DATA (STATIC)
    // =========================
    val customer: CustomerCurrentCustomer? = null,

    // =========================
    // STATIC LIST FROM BACKEND
    // =========================
    val filteredPassengerRides: List<PassengerRideCustomer> = emptyList(),
    val listPassengerRides: List<PassengerRideCustomer> = emptyList(),

    // ⬇️ sebelumnya: List<TerminalDepartureCustomer>
    val listTerminals: List<TerminalCustomer> = emptyList(),

    val listPaymentMethods: List<PaymentMethodCustomer> = emptyList(),
    val listPassengerPricing: List<PassengerPricingCustomer> = emptyList(),

    // =========================
    // PROGRESS (USER CHOICES)
    // =========================
    val selectedRide:   PassengerRideCustomer? = null,
    val vehicleType: VehicleType = VehicleType.UNKNOWN,

    val selectedDriver: DriverCustomer? = null,

    // ⬇️ sebelumnya: TerminalDepartureCustomer? / TerminalArrivalCustomer?
    val selectedDepartureTerminal: TerminalCustomer? = null,
    val selectedArrivalTerminal:   TerminalCustomer? = null,

    val selectedPricing: PassengerPricingCustomer? = null,
    val selectedPaymentMethod: PaymentMethodCustomer? = null,

    val totalPrice: Int = 0,

    val step: BookingStep = BookingStep.SELECT_RIDE,
    val selectedDate: LocalDate? = null,

    val paymentUiMode: PaymentUiMode = PaymentUiMode.STATUS,

    // =========================
    // GENERATED BY BACKEND
    // =========================
    val booking: PassengerRideBookingCustomer? = null,
    val transaction: PassengerTransactionCustomer? = null
)
